[build-system]
requires = ["sphinx-theme-builder >= 0.2.0a7"]
build-backend = "sphinx_theme_builder"

[tool.sphinx-theme-builder]
node-version = "16.13.2"
theme-name = "pydata_sphinx_theme"
additional-compiled-static-assets = [
  "webpack-macros.html",
  "vendor/",
]

[project]
authors = [{name = "xinetzone", email = "735613050@qq.com"}]
dynamic = ["version", "description"]
license = {file = "LICENSE"}
name = "xyzstyle"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "sphinx>=3.5.4,<5",
  "beautifulsoup4",
  "docutils!=0.17.0",
  "packaging",
  "d2py",
  "pydata_sphinx_theme"
]

maintainers = [
  {name = "xinetzone", email = "735613050@qq.com"},
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Framework :: Sphinx",
  "Framework :: Sphinx :: Theme",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
doc = [
  "numpydoc",
  "pytest-regressions",
  "sphinxext-rediraffe",
  "sphinx-copybutton",
  "myst-nb",
  "pandas",
  "pytest",
  "pytest-regressions",
  "sphinxext-rediraffe",
  "sphinx-sitemap",
  # For demo examples
  "jupyter_sphinx",
  "plotly",
  "numpy",
  "xarray",
]
test = [
  "pytest",
  "xyzstyle[doc]",
]
coverage = [
  "pytest-cov",
  "codecov",
  "xyzstyle[test]",
]
dev = [
  "pyyaml",
  "pre-commit",
  "nox",
  "xyzstyle[coverage]",
]

[project.entry-points]
"sphinx.html_themes" = {xyzstyle = "xyzstyle"}